### ISSUE TITLE
implement redirect in the parseArticles hook to increase compatibility with other news extensions

### ISSUE THREAD

**Issue by DVeris** [fritzmg/contao-simple-news-urls#7]
for example

change the file
\system\modules\simple_news_urls\modules\ModuleNewsReaderRedirect.php

to

class ModuleNewsReaderRedirect extends \ModuleNewsReader
{
bla bla
}

there has to be a bug, but...

this file isn't used

**Comment by DVeris** [comment]
$this->redirect( \SimpleNewsUrls::buildUrl( $objPage->row(), \Input::get('auto_item') ) );
this line isn't used

and 303 redirect not execute

**Comment by DVeris** [comment]
and maybe use 301 redirect?

**Comment by fritzmg** [comment]
> for example
> 
> change the file
> \system\modules\simple_news_urls\modules\ModuleNewsReaderRedirect.php
> 
> to
> 
> class ModuleNewsReaderRedirect extends \ModuleNewsReader
> {
> bla bla
> }
> 
> there has to be a bug, but...
> 
> this file isn't used

`ModuleNewsReaderRedirect` replaces the default `Contao\ModulesNewsreader`: [simple_news_urls/config/config.php#L21](https://github.com/fritzmg/contao-simple-news-urls/blob/1.1.2/system/modules/simple_news_urls/config/config.php#L21). If the file is "not being used" as you say, then some other extension you have installed replaces it as well and is loaded after this extension.

Maybe I'll instead try to implement this redirect in a `parseArticle` hook instead, so that the extension can be used more independently of other news extensions.

**Comment by fritzmg** [comment]
> $this->redirect( \SimpleNewsUrls::buildUrl( $objPage->row(), \Input::get('auto_item') ) );
> this line isn't used
> 
> and 303 redirect not execute

Under what conditions is it not being used?

**Comment by fritzmg** [comment]
> and maybe use 301 redirect?

Sure, why not :)

**Comment by DVeris** [comment]
you are right...

> Maybe I'll instead try to implement this redirect in a parseArticle hook instead, so that the extension can be used more independently of other news extensions.

yes, please

by default your extension uses 303 redirect
https://docs.contao.org/books/api/functions/Controller.redirect.html

**Comment by DVeris** [comment]
the module "tags" disturbs
https://contao.org/en/extension-list/view/tags.30020029.en.html

**Comment by DVeris** [comment]
$GLOBALS['FE_MOD']['news']['newsreader'][]

maybe? or it not work?

**Comment by fritzmg** [comment]
No, it won't work this way.

**Comment by fritzmg** [comment]
Released in version `2.0.0`.

**Comment by fritzmg** [comment]
With version `2.0.0` you can also create a canonical tag instead of a redirect (see README).
